name: Auto label bump PRs

on:
    pull_request:
        types: [opened]

jobs:
    label:
        if: github.actor == 'github-actions[bot]'
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - name: Add pr-pull label
              uses: actions-ecosystem/action-add-labels@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  labels: pr-pull
