name: Auto bump Homebrew formulae

on:
    schedule:
        - cron: "0 3 * * *" # daily at 03:00 UTC
    workflow_dispatch:

jobs:
    livecheck-bump:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - name: Bump outdated formulae (livecheck)
              uses: dawidd6/action-homebrew-bump-formula@v5
              with:
                  token: ${{ secrets.HOMEBREW_BUMP_TOKEN }}
                  tap: jassielof/homebrew-tap
                  livecheck: true
                  user_name: github-actions[bot]
                  user_email: github-actions[bot]@users.noreply.github.com
